# Generated by Django 5.2 on 2026-04-03 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('scenario_data', models.JSONField(help_text='Конфигурация симуляции (узлы, связи, команды)', verbose_name='Данные сценария')),
                ('hints', models.TextField(blank=True, help_text='Подсказки по командам терминала', null=True, verbose_name='Подсказки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Лабораторная работа',
                'verbose_name_plural': 'Лабораторные работы',
            },
        ),
        migrations.CreateModel(
            name='LabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено?')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('commands_history', models.JSONField(default=list, verbose_name='История команд')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.lab', verbose_name='Лабораторная работа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс лабы',
                'verbose_name_plural': 'Прогресс лаб',
            },
        ),
    ]
