# Generated by Django 5.2 on 2026-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='hints',
            field=models.TextField(blank=True, help_text='Подсказки по командам терминала', null=True),
        ),
    ]
