# Generated by Django 5.2 on 2026-04-03 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_resource_options_and_more'),
        ('laboratory', '0002_lab_hints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'Лабораторная работа', 'verbose_name_plural': 'Лабораторные работы'},
        ),
        migrations.AlterModelOptions(
            name='labprogress',
            options={'verbose_name': 'Прогресс лабы', 'verbose_name_plural': 'Прогресс лаб'},
        ),
        migrations.AlterField(
            model_name='lab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='hints',
            field=models.TextField(blank=True, help_text='Подсказки по командам терминала', null=True, verbose_name='Подсказки'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='courses.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='scenario_data',
            field=models.JSONField(help_text='Конфигурация симуляции (узлы, связи, команды)', verbose_name='Данные сценария'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='labprogress',
            name='commands_history',
            field=models.JSONField(default=list, verbose_name='История команд'),
        ),
        migrations.AlterField(
            model_name='labprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='labprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено?'),
        ),
        migrations.AlterField(
            model_name='labprogress',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.lab', verbose_name='Лабораторная работа'),
        ),
        migrations.AlterField(
            model_name='labprogress',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='labprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
