# Generated by Django 5.2 on 2026-06-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_lab_options_alter_labprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Завершено?'),
        ),
    ]
