# Generated by Django 5.2 on 2026-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_alter_labprogress_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (каз)'),
        ),
        migrations.AddField(
            model_name='lab',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (каз)'),
        ),
    ]
