# Generated by Django 5.2 on 2026-06-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_lab_description_kk_lab_title_kk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Лабораторная работа', 'verbose_name_plural': 'Лабораторные работы'},
        ),
        migrations.AlterModelOptions(
            name='labprogress',
            options={'ordering': ['-last_activity'], 'verbose_name': 'Прогресс лабы', 'verbose_name_plural': 'Прогресс лаб'},
        ),
        migrations.AddField(
            model_name='lab',
            name='category',
            field=models.CharField(choices=[('basic', 'Основы'), ('intermediate', 'Продвинутый'), ('advanced', 'Эксперт')], default='basic', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='lab',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=20, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='lab',
            name='estimated_time',
            field=models.IntegerField(default=30, help_text='Оценочное время выполнения в минутах', verbose_name='Оценочное время (мин)'),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна?'),
        ),
        migrations.AddField(
            model_name='lab',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения в списке', verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='lab',
            name='tags',
            field=models.CharField(blank=True, help_text='Теги через запятую, например: OSI, IP, Routing', max_length=200, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='lab',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='labprogress',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AddField(
            model_name='labprogress',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='labprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='labprogress',
            name='time_spent',
            field=models.IntegerField(default=0, verbose_name='Время затрачено (сек)'),
        ),
    ]
