# Generated by Django 5.2 on 2026-06-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_onboarding',
            field=models.BooleanField(default=False, verbose_name='Онбординг пройден'),
        ),
    ]
