# Generated by Django 5.2 on 2026-06-13 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTopology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название топологии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_topologies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сетевая топология',
                'verbose_name_plural': 'Сетевые топологии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя устройства')),
                ('type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('hub', 'Hub'), ('pc', 'PC'), ('server', 'Server')], max_length=20, verbose_name='Тип устройства')),
                ('x', models.IntegerField(default=0, verbose_name='Позиция X')),
                ('y', models.IntegerField(default=0, verbose_name='Позиция Y')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Статус')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP-адрес')),
                ('subnet_mask', models.CharField(blank=True, max_length=45, null=True, verbose_name='Маска подсети')),
                ('gateway', models.CharField(blank=True, max_length=45, null=True, verbose_name='Шлюз')),
                ('dns', models.CharField(blank=True, max_length=45, null=True, verbose_name='DNS')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hostname')),
                ('interfaces', models.JSONField(blank=True, default=dict, verbose_name='Интерфейсы')),
                ('routes', models.JSONField(blank=True, default=list, verbose_name='Маршруты')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='network_simulator.networktopology', verbose_name='Топология')),
            ],
            options={
                'verbose_name': 'Сетевое устройство',
                'verbose_name_plural': 'Сетевые устройства',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_type', models.CharField(choices=[('auto', 'Auto'), ('straight', 'Straight Through'), ('crossover', 'Cross Over'), ('fiber', 'Fiber')], default='auto', max_length=20, verbose_name='Тип кабеля')),
                ('status', models.CharField(default='connected', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='network_simulator.networkdevice', verbose_name='Исходное устройство')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='network_simulator.networkdevice', verbose_name='Целевое устройство')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='network_simulator.networktopology', verbose_name='Топология')),
            ],
            options={
                'verbose_name': 'Сетевое соединение',
                'verbose_name_plural': 'Сетевые соединения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('icmp', 'ICMP (Ping)'), ('tcp', 'TCP'), ('udp', 'UDP'), ('http', 'HTTP')], default='icmp', max_length=20, verbose_name='Протокол')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Результат симуляции')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='Статус')),
                ('packet_path', models.JSONField(blank=True, default=list, verbose_name='Путь пакета')),
                ('source_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_simulations', to='network_simulator.networkdevice', verbose_name='Исходное устройство')),
                ('target_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_simulations', to='network_simulator.networkdevice', verbose_name='Целевое устройство')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='network_simulator.networktopology', verbose_name='Топология')),
            ],
            options={
                'verbose_name': 'Сессия симуляции',
                'verbose_name_plural': 'Сессии симуляции',
                'ordering': ['-started_at'],
            },
        ),
    ]
