# Generated by Codex on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktopology',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Отправлено преподавателю'),
        ),
        migrations.AddField(
            model_name='networktopology',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
