# Generated by Django 5.2 on 2026-06-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_simulator', '0002_topology_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationsession',
            name='protocol',
            field=models.CharField(choices=[('icmp', 'ICMP (Ping)')], default='icmp', max_length=20, verbose_name='Протокол'),
        ),
        migrations.CreateModel(
            name='DHCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.CharField(max_length=45, verbose_name='Начальный IP')),
                ('end_ip', models.CharField(max_length=45, verbose_name='Конечный IP')),
                ('subnet_mask', models.CharField(default='255.255.255.0', max_length=45, verbose_name='Маска подсети')),
                ('gateway', models.CharField(blank=True, max_length=45, null=True, verbose_name='Шлюз')),
                ('dns', models.CharField(blank=True, max_length=45, null=True, verbose_name='DNS')),
                ('lease_time', models.IntegerField(default=86400, verbose_name='Время аренды (сек)')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_server', to='network_simulator.networkdevice', verbose_name='Устройство')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_servers', to='network_simulator.networktopology', verbose_name='Топология')),
            ],
            options={
                'verbose_name': 'DHCP-сервер',
                'verbose_name_plural': 'DHCP-серверы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PacketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.JSONField(default=list, verbose_name='Маршрут')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('pending', 'В обработке')], default='pending', max_length=20, verbose_name='Статус')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='network_simulator.simulationsession', verbose_name='Сессия симуляции')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_packets', to='network_simulator.networkdevice', verbose_name='Источник')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_packets', to='network_simulator.networkdevice', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Лог пакетов',
                'verbose_name_plural': 'Логи пакетов',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TerminalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='Команда')),
                ('output', models.TextField(verbose_name='Вывод')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_history', to='network_simulator.networkdevice', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'История терминала',
                'verbose_name_plural': 'История терминала',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название VLAN')),
                ('color', models.CharField(choices=[('#9b59b6', 'Фиолетовый'), ('#3498db', 'Синий'), ('#2ecc71', 'Зеленый'), ('#e74c3c', 'Красный'), ('#f1c40f', 'Желтый'), ('#e67e22', 'Оранжевый')], default='#9b59b6', max_length=20, verbose_name='Цвет')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='network_simulator.networktopology', verbose_name='Топология')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLAN',
                'ordering': ['vlan_id'],
                'unique_together': {('topology', 'vlan_id')},
            },
        ),
    ]
