# Generated by Django 5.2 on 2026-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_simulator', '0003_alter_simulationsession_protocol_dhcpserver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='type',
            field=models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('hub', 'Hub'), ('pc', 'PC'), ('server', 'Server'), ('firewall', 'Firewall'), ('ap', 'Access Point')], max_length=20, verbose_name='Тип устройства'),
        ),
    ]
