# Generated by Django 5.2 on 2026-04-03 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('slug', models.SlugField(unique=True, verbose_name='URL слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='Подсказка')),
                ('difficulty', models.CharField(choices=[('Easy', 'Легкий'), ('Intermediate', 'Средний'), ('Hard', 'Сложный')], default='Intermediate', max_length=20, verbose_name='Сложность')),
                ('category', models.CharField(choices=[('Conceptual Analysis', 'Концептуальный анализ'), ('Practical Application', 'Практическое применение'), ('Troubleshooting', 'Поиск неисправностей')], default='Conceptual Analysis', max_length=50, verbose_name='Категория')),
                ('type', models.CharField(choices=[('multiple_choice', 'Выбор варианта'), ('sorting', 'Сортировка'), ('matching', 'Сопоставление'), ('text_input', 'Ввод текста')], default='multiple_choice', max_length=20, verbose_name='Тип вопроса')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Секция (блок)')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок (для сортировки)')),
                ('pair_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пара (для сопоставления)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('resource_type', models.CharField(choices=[('Video', 'Видео'), ('PDF', 'PDF документ'), ('Link', 'Внешняя ссылка'), ('Other', 'Другое')], default='Other', max_length=20, verbose_name='Тип ресурса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.module', verbose_name='Модуль')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
        migrations.CreateModel(
            name='UsabilityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.PositiveSmallIntegerField(verbose_name='Я думаю, что я хотел бы часто использовать эту систему')),
                ('q2', models.PositiveSmallIntegerField(verbose_name='Я нашел систему излишне сложной')),
                ('q3', models.PositiveSmallIntegerField(verbose_name='Я думаю, что система была легкой в использовании')),
                ('q4', models.PositiveSmallIntegerField(verbose_name='Я думаю, что мне понадобится помощь технического специалиста, чтобы пользоваться этой системой')),
                ('q5', models.PositiveSmallIntegerField(verbose_name='Я нашел, что различные функции в этой системе были хорошо интегрированы')),
                ('q6', models.PositiveSmallIntegerField(verbose_name='Я думаю, что в этой системе было слишком много несогласованности')),
                ('q7', models.PositiveSmallIntegerField(verbose_name='Я бы вообразил, что большинство людей научатся пользоваться этой системой очень быстро')),
                ('q8', models.PositiveSmallIntegerField(verbose_name='Я нашел систему очень громоздкой в использовании')),
                ('q9', models.PositiveSmallIntegerField(verbose_name='Я чувствовал себя очень уверенно, пользуясь системой')),
                ('q10', models.PositiveSmallIntegerField(verbose_name='Мне нужно было узнать много вещей, прежде чем я смог приступить к работе с этой системой')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка юзабилити',
                'verbose_name_plural': 'Оценки юзабилити',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(blank=True, null=True, verbose_name='Ввод пользователя')),
                ('user_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок пользователя')),
                ('matched_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сопоставленный текст')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно?')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.choice', verbose_name='Выбранный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Затраченное время (сек)')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Количество ошибок')),
                ('completed_at', models.DateTimeField(auto_now=True, verbose_name='Дата завершения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен?')),
                ('share_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Токен доступа')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='Модуль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
