# Generated by Django 5.2 on 2026-03-21 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='errors_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ошибок'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Время (в секундах)'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно?')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.choice', verbose_name='Выбранный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
