# Generated by Django 5.2 on 2026-03-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_userprogress_errors_count_userprogress_time_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Conceptual Analysis', 'Концептуальный анализ'), ('Practical Application', 'Практическое применение'), ('Troubleshooting', 'Поиск неисправностей')], default='Conceptual Analysis', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Легкий'), ('Intermediate', 'Средний'), ('Hard', 'Сложный')], default='Intermediate', max_length=20, verbose_name='Сложность'),
        ),
    ]
