# Generated by Django 5.2 on 2026-03-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='modules/files/', verbose_name='Дополнительный файл'),
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/images/', verbose_name='Изображение модуля'),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
    ]
