# Generated by Django 5.2 on 2026-04-03 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module_is_custom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок (для сортировки)'),
        ),
        migrations.AddField(
            model_name='choice',
            name='pair_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пара (для сопоставления)'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Выбор варианта'), ('sorting', 'Сортировка'), ('matching', 'Сопоставление'), ('text_input', 'Ввод текста')], default='multiple_choice', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='matched_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сопоставленный текст'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_input',
            field=models.TextField(blank=True, null=True, verbose_name='Ввод пользователя'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок пользователя'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='share_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.choice', verbose_name='Выбранный ответ'),
        ),
    ]
