# Generated by Django 5.2 on 2026-04-03 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_choice_options_choice_order_choice_pair_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Ресурс', 'verbose_name_plural': 'Ресурсы'},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='module',
            name='video_url',
        ),
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Секция (блок)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.module', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL слаг'),
        ),
        migrations.AlterField(
            model_name='question',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('Video', 'Видео'), ('PDF', 'PDF документ'), ('Link', 'Внешняя ссылка'), ('Other', 'Другое')], default='Other', max_length=20, verbose_name='Тип ресурса'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Затраченное время (сек)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='UsabilityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.PositiveSmallIntegerField(verbose_name='Я думаю, что я хотел бы часто использовать эту систему')),
                ('q2', models.PositiveSmallIntegerField(verbose_name='Я нашел систему излишне сложной')),
                ('q3', models.PositiveSmallIntegerField(verbose_name='Я думаю, что система была легкой в использовании')),
                ('q4', models.PositiveSmallIntegerField(verbose_name='Я думаю, что мне понадобится помощь технического специалиста, чтобы пользоваться этой системой')),
                ('q5', models.PositiveSmallIntegerField(verbose_name='Я нашел, что различные функции в этой системе были хорошо интегрированы')),
                ('q6', models.PositiveSmallIntegerField(verbose_name='Я думаю, что в этой системе было слишком много несогласованности')),
                ('q7', models.PositiveSmallIntegerField(verbose_name='Я бы вообразил, что большинство людей научатся пользоваться этой системой очень быстро')),
                ('q8', models.PositiveSmallIntegerField(verbose_name='Я нашел систему очень громоздкой в использовании')),
                ('q9', models.PositiveSmallIntegerField(verbose_name='Я чувствовал себя очень уверенно, пользуясь системой')),
                ('q10', models.PositiveSmallIntegerField(verbose_name='Мне нужно было узнать много вещей, прежде чем я смог приступить к работе с этой системой')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка юзабилити',
                'verbose_name_plural': 'Оценки юзабилити',
            },
        ),
    ]
