# Generated by Django 5.2 on 2026-04-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_userprogress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.module', verbose_name='Модуль'),
        ),
    ]
