# Generated by Django 5.2 on 2026-04-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_module_file_module_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Изменен преподавателем'),
        ),
    ]
