# Generated by Django 5.2 on 2026-06-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_module_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Объяснение'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Завершен?'),
        ),
    ]
