# Generated by Django 5.2 on 2026-06-10 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_question_explanation_alter_module_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('project_description', models.TextField(verbose_name='Описание проекта и обоснование архитектуры')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақша')], default='ru', max_length=2, verbose_name='Язык проекта')),
                ('file', models.FileField(blank=True, null=True, upload_to='final_projects/', verbose_name='Файл проекта')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('reviewing', 'Проверяется'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Обратная связь от преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_projects', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_projects', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Финальный проект',
                'verbose_name_plural': 'Финальные проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
