# Generated by Django 5.2 on 2026-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_finalproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст ответа (каз)'),
        ),
        migrations.AddField(
            model_name='module',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (каз)'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название модуля (каз)'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса (каз)'),
        ),
    ]
