# Generated by Django 5.2 on 2026-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_choice_text_kk_module_description_kk_module_name_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='pair_text_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пара (для сопоставления) (каз)'),
        ),
    ]
